name: Depo_Market_1_16_5
version: '${version}'
main: depo_market.depo_market_1_16_5.Depo_Market_1_16_5
api-version: 1.16
authors: [ Deponn ]
description: Plugin that add market and economy to minecraft


commands: #自作プラグインのコマンドを宣言
  initialize_market:
    description: マーケットのデータを初期化する
    usage: /initialize_market
  start_market:
    description: マーケットを開始
    usage: /start_market
    permission: market
  stop_market:
    description: マーケットを止める
    usage: /stop_market
    permission: market
  place_customer:
    description: マーケット窓口を一人分実体化
    usage: /place_customer
    permission: market
  kill_all_customer:
    description: 全マーケット窓口を削除
    usage: /kill_all_customer
    permission: market
  tax:
    description: 徴税
    usage: /tax [チーム名] [金額]
    permission: market
  give_money:
    description: お金をあげる
    usage: /give_money [チーム名] [金額]
    permission: market
  set_disadvantage:
    description: 借金した時のデバフを決める
    usage: /set_disadvantage [デバフ名]
    permission: market
  reload_team:
    description: チームが新たに作られた時用
    usage: /  reload_team
    permission: market

permissions:
  market:
    description: op only
    default: op