name: Depo_Market_1_16_5
version: '${version}'
main: depo_market.depo_market_1_16_5.Depo_Market_1_16_5
api-version: 1.16
authors: [ Deponn ]
description: Plugin that add market and economy to minecraft


commands: #自作プラグインのコマンドを宣言
  EnableDpPlugin:
    description: プラグインを有効にする
    usage: /    EnableDpPlugin
    permission: market
  DisableDpPlugin:
    description: プラグインを無効にする
    usage: /    DisableDpPlugin
    permission: market
  DpStartMarket:
    description: マーケットを開始
    usage: /  DpStartMarket
    permission: market
  DpStopMarket:
    description: マーケットを止める
    usage: /  DpStopMarket
    permission: market
  DpPlaceCustomer:
    description: マーケット窓口を一人分実体化
    usage: /  DpPlaceCustomer
    permission: market
  DpSetPointCustomer:
    description: マーケット窓口を一人分実体化
    usage: /  DpSetPointCustomer
    permission: market
  DpKillAllCustomer:
    description: 全マーケット窓口を削除
    usage: /  DpKillAllCustomer
    permission: market
  DpGiveMoney:
    description: お金をあげる
    usage: /  DpGiveMoney [チーム名] [金額]
    permission: market
  DpSetDisadvantage:
    description: 借金した時のデバフを決める
    usage: /  DpSetDisadvantage [デバフ名]
    permission: market
  DpLookTeams:
    description: 全チームの所持金を見る
    usage: /   DpLoadNewTeams
    permission: market
  DpLookScore:
    description: スコアを見る
    usage: /     DpLookScore
    permission: market

permissions:
  market:
    description: op only
    default: op